version: '3'
services:
  frontend:
    build: .
    # Node.jsのグローバル変数です。開発用途なのでdevelopmentを指定します。
    environment:
      - NODE_ENV=development
    volumes:
      - ./app/my-app:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c 'npm start'
    ports:
      - 3000:3000
    tty: true
  